apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moon2-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orcunbalcilar/moon-gitops
    targetRevision: master
    path: dev
    helm:
      valueFiles:
        - values.yaml
      chart: moon2
      repoURL: https://charts.aerokube.com/
      version: 2.7.9
  destination:
    server: https://kubernetes.default.svc
    namespace: moon-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
