apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moon
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.aerokube.com/
      chart: moon2
      targetRevision: 2.7.9
      helm:
        valueFiles:
          - $values/dev/values.yaml
    - repoURL: https://github.com/orcunbalcilar/moon-gitops
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: moon-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  #ignoreDifferences:
   # - group: security.openshift.io
    #  kind: SecurityContextConstraints
     # name: moon
      #jsonPointers:
       # - /seccompProfiles
