customIngress:
  enabled: true
  annotations:
    route.openshift.io/termination: edge
  ingressClassName: openshift-default
  host: moon-dev.apps-crc.testing
  tls: []
  paths:
  - path: /wd/hub
    port: 4444
  - path: /cypress
    port: 4444
  - path: /playwright
    port: 4444
  - path: /devtools
    port: 4444
  - path: /metrics
    port: 4444
  - path: /api
    port: 9090
  - path: /ui
    port: 9090
  - path: /
    port: 8080

ingress:
  enabled: true
  host: moon-dev.apps-crc.testing
  proxyConnectTimeout: 1900
  proxySendTimeout: 1900
  proxyReadTimeout: 1900
  proxyBodySize: 128m
  openshift: true

sccAnnotations: 
  kubernetes.io/description: 'Like the restricted SCC, but with the seccompProfiles turn off'

deployment:
  replicas: 1
  experimentalUI: true
  oldUI: true

configs:
  default:
    serviceAccountName: default
    sessionTimeout: 5m
    user:
      id: 4096
      name: user
    group:
      id: 4096
      name: user
    containers:
      browser:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
      ca-certs:
        repository: quay.io/aerokube/ca-certs
        resources:
          limits:
            cpu: 200m
            memory: 32Mi
          requests:
            cpu: 100m
            memory: 32Mi
      proxy:
        repository: quay.io/aerokube/tinyproxy
        version: 1.11.2-1
        resources:
          limits:
            cpu: 200m
            memory: 32Mi
          requests:
            cpu: 100m
            memory: 32Mi
      defender:
        repository: quay.io/aerokube/defender
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      video-recorder:
        repository: quay.io/aerokube/video-recorder
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 2Gi
      vnc-server:
        repository: quay.io/aerokube/x11vnc
        version: 0.9.16-1
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      window-manager:
        repository: quay.io/aerokube/openbox
        version: 3.6.1-1
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      sound-server:
        repository: quay.io/aerokube/pulseaudio
        version: 17.0.0-1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      x-server:
        repository: quay.io/aerokube/xvfb
        version: 21.1-1
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      additional-fonts:
        repository: quay.io/aerokube/fonts
        version: 1.0.0-1
        resources:
          limits:
            cpu: 200m
            memory: 32Mi
          requests:
            cpu: 100m
            memory: 32Mi
      har:
        repository: quay.io/aerokube/har
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
    storage:
      accessKey: ""
      bucket: ""
      endpoint: ""
      filename: ""
      pattern: ""
      secretKey: ""
      noProxy: ""
      httpProxy: ""
      httpsProxy: ""

browsers:
  default:
    selenium:
      MicrosoftEdge:
        repository: quay.io/browser/microsoft-edge-stable
        default: 141.0.3537.92-11
      chrome:
        repository: quay.io/browser/google-chrome-stable
        default: 141.0.7390.122-11
      chrome-for-testing:
        repository: quay.io/browser/chrome-for-testing
        default: 141.0.7390.122
      firefox:
        repository: quay.io/browser/firefox-mozilla-build
        default: 144.0.0
      opera:
        repository: quay.io/browser/opera-stable
        default: 122.0.5643.142-12
      safari:
        repository: quay.io/browser/safari
        default: "18.4"
    cypress:
      electron:
        repository: quay.io/browsers/cypress-electron
        default: latest
      chromium:
        repository: quay.io/browsers/cypress-chromium
        default: latest
      chrome:
        repository: quay.io/browsers/cypress-chrome
        default: latest
      firefox:
        repository: quay.io/browsers/cypress-firefox
        default: latest
      edge:
        repository: quay.io/browsers/cypress-edge
        default: latest
    playwright:
      chrome:
        repository: quay.io/browser/playwright-chrome
        default: v1.51.0
      chromium:
        repository: quay.io/browser/playwright-chromium
        default: v1.51.0
      firefox:
        repository: quay.io/browser/playwright-firefox
        default: v1.51.0
      webkit:
        repository: quay.io/browser/playwright-webkit
        default: v1.51.0
    devtools:
      chrome:
        repository: quay.io/browser/devtools-google-chrome-stable

quota:
  moon:
    namespace: moon-dev

licenseSecretName: moon-license

rbac:
  enabled: true