apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moon2-uat
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.aerokube.com/
      chart: moon2
      targetRevision: 2.7.9
      helm:
        valueFiles:
          - $values/uat/values.yaml
    - repoURL: https://github.com/orcunbalcilar/moon-gitops
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: moon-uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
